import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { Pagination } from "../components/Pagination";

const pageSize = 9;
export function ResourcesPage() { const [resources, setResources] = useState([]); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [status, setStatus] = useState("loading"); const [error, setError] = useState(""); useEffect(() => { async function load() { try { const { data, error: loadError } = await supabase.from("resources").select("id,title,description,url,tags,created_at").order("created_at", { ascending: false }); if (loadError) throw loadError; setResources(data ?? []); setStatus("ready"); } catch { setError("We could not load resources right now. Please try again later."); setStatus("error"); } } load(); }, []); const filtered = useMemo(() => resources.filter((item) => `${item.title} ${item.description ?? ""} ${tagsText(item.tags)}`.toLowerCase().includes(query.toLowerCase())), [resources, query]); const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize)); const visible = filtered.slice((page - 1) * pageSize, page * pageSize); return <><PageIntro eyebrow="Member library" title="Resources for the work behind the work." text="Search materials shared by the ATAS-LASU community—from study support to creative references." /><section className="mx-auto max-w-7xl px-6 py-14"><input type="search" value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} placeholder="Search resources" className="w-full border border-line-subtle bg-stage-charcoal px-5 py-4 text-chalk-cream outline-none focus:border-theatre-amber" />{status === "loading" && <Loading label="Loading resources…" />}{status === "error" && <Message tone="error">{error}</Message>}{status === "ready" && (filtered.length ? <><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{visible.map((resource) => <ResourceCard key={resource.id} resource={resource} />)}</div><Pagination page={page} pageCount={pageCount} onChange={setPage} /></> : <Message>No resources match that search yet.</Message>)}</section></>; }
function ResourceCard({ resource }) { const tags = tagsText(resource.tags).split(",").map((tag) => tag.trim()).filter(Boolean); return <article className="stage-card flex min-h-64 flex-col p-6"><p className="text-xs text-stone-muted">Added {resource.created_at ? new Date(resource.created_at).toLocaleDateString() : "recently"}</p><h2 className="mt-4 font-display text-3xl text-chalk-cream">{resource.title}</h2><p className="mt-4 text-sm leading-6 text-chalk-cream/80">{resource.description || "No description has been added yet."}</p><div className="mt-auto pt-6">{tags.length > 0 && <p className="mb-4 text-xs font-semibold tracking-[.1em] text-theatre-amber">{tags.join(" · ")}</p>}<a href={resource.url} target="_blank" rel="noreferrer" className="stage-link">Open resource →</a></div></article>; }
function tagsText(tags) { return Array.isArray(tags) ? tags.join(",") : typeof tags === "string" ? tags : ""; }
export function PageIntro({ eyebrow, title, text }) { return <section className="bg-stage-charcoal px-6 py-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[.12em] text-theatre-amber">{eyebrow}</p><h1 className="mt-6 max-w-4xl font-display text-5xl leading-[.9] text-chalk-cream sm:text-7xl">{title}</h1><p className="mt-7 max-w-2xl text-[15px] leading-7 text-chalk-cream/85">{text}</p></div></section>; }
export function Loading({ label }) { return <p className="mt-10 text-chalk-cream/75">{label}</p>; }
export function Message({ children, tone }) { return <p role={tone === "error" ? "alert" : "status"} className="mt-10 border-l-2 border-theatre-amber bg-stage-surface p-5 text-chalk-cream">{children}</p>; }
